FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=8501
EXPOSE $PORT

CMD streamlit run src/dashboard/app.py --server.port=$PORT --server.address=0.0.0.0